parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    S(KC_QUOT): '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
    KC_TAB: '$$phosphor:bold/caret-line-right$$'
    C(KC_TAB): '$$phosphor:bold/text-outdent$$'
    C(S(KC_TAB)): '$$phosphor:bold/text-indent$$'
    KC_SPC: '󱁐'
    KC_LSFT: '󰘶'
    KC_RSFT: '󰘶'
    KC_A_S: '󰘶  A'
    KC_O_S: '󰘶  O'
    KC_LALT: '󰘵'
    KC_RALT: '󰘵'
    KC_R_A: '󰘵  R'
    KC_I_A: '󰘵  I'
    KC_LGUI: '󰘳'
    KC_RGUI: '󰘳'
    KC_S_G: '󰘳  S'
    KC_E_G: '󰘳  E'
    KC_LCTL: '󰘴'
    KC_RCTL: '󰘴'
    KC_T_C: '󰘴  T'
    KC_N_C: '󰘴  N'
    KC_ENT: '$$phosphor:bold/key-return$$'
    KC_BSPC: '$$phosphor:bold/backspace$$'
    KC_DEL: '$$phosphor:bold/eraser$$'
    KC_DOWN: '$$phosphor:bold/arrow-down$$'
    KC_UP: '$$phosphor:bold/arrow-up$$'
    KC_LEFT: '$$phosphor:bold/arrow-left$$'
    KC_RIGHT: '$$phosphor:bold/arrow-right$$'
    LED_TOG: '$$phosphor:bold/lightbulb$$'
    KC_VOLD: '$$phosphor:bold/speaker-low$$'
    KC_VOLU: '$$phosphor:bold/speaker-high$$'
    KC_MUTE: '$$phosphor:bold/speaker-slash$$'
    KC_MPRV: '$$phosphor:bold/skip-back$$'
    KC_MNXT: '$$phosphor:bold/skip-forward$$'
    KC_MSTP: '$$phosphor:bold/stop$$'
    KC_MPLY: '$$phosphor:bold/play-pause$$'
    KC_HOME: '$$phosphor:bold/caret-line-up$$'
    KC_PGUP: '$$phosphor:bold/caret-up$$'
    KC_END: '$$phosphor:bold/caret-line-down$$'
    KC_PGDN: '$$phosphor:bold/caret-down$$'
    KC_PRINT_SCREEN: '$$phosphor:bold/monitor$$'
    QK_LLCK: '$$phosphor:bold/lock$$'
    MS_LEFT: '$$phosphor:bold/cursor$$'
    MS_UP: '$$phosphor:bold/cursor$$'
    MS_RGHT: '$$phosphor:bold/cursor$$'
    MS_DOWN: '$$phosphor:bold/cursor$$'
    MS_WHLD: '$$phosphor:bold/caret-down$$'
    MS_WHLU: '$$phosphor:bold/caret-up$$'
    MS_BTN1: '$$phosphor:bold/mouse-left-click$$'
    MS_BTN2: '$$phosphor:bold/mouse-right-click$$'
    MS_BTN3: '$$phosphor:bold/mouse-middle-click$$'
    STN_N1: '#1'
    STN_N2: '#2'
    STN_N3: '#3'
    STN_N4: '#4'
    STN_N5: '#5'
    STN_N6: '#6'
    STN_N7: '#7'
    STN_N8: '#8'
    STN_N9: '#9'
    STN_NA: '#A'
    STN_NB: '#B'
    STN_S1: 'S-'
    STN_TL: 'T-'
    STN_PL: 'P-'
    STN_HL: 'H-'
    STN_ST1: '*'
    STN_ST3: '*'
    STN_FR: '-F'
    STN_PR: '-P'
    STN_LR: '-L'
    STN_TR: '-T'
    STN_DR: '-D'
    STN_S2: 'S-'
    STN_KL: 'K-'
    STN_WL: 'W-'
    STN_RL: 'R-'
    STN_ST2: '*'
    STN_ST4: '*'
    STN_RR: '-R'
    STN_BR: '-B'
    STN_GR: '-G'
    STN_SR: '-S'
    STN_ZR: '-Z'
    STN_NC: '#C'
    STN_A: 'A'
    STN_O: 'O'
    STN_E: 'E'
    STN_U: 'U'
    C_CAPSWORD: "󰪛 WORD"
